quarkus.log.category."org.kohsuke.github".level=FINEST
quarkus.rest-client.follow-redirects=true
quarkus.package.jar.type=uber-jar

quarkus.log.console.enable=false
quarkus.log.file.enable=true
quarkus.log.file.path=mcpgithub-quarkus.log

quarkus.profile=local

quarkus.oidc.provider=github

#Set your GitHub OAuth2 application credentials here, 
#Or, set via env vars -Dquarkus.oidc.client-id=...

#quarkus.oidc.client-id=PUT GITHUB OAUTH2 APP CLIENT ID HERE
#quarkus.oidc.credentials.secret=PUT GITHUB OAUTH2 APP SECRET HERE

quarkus.oidc.cache-user-info-in-idtoken=true
quarkus.oidc.authentication.scopes=user:email,read:user,write:issues